### PR TITLE
Use native modules

### PR DESCRIPTION
**Pull request by jboxman**
- Initial pass using amd-to-as6
- Fix paths
- Fix test/test.js

### CODE REVIEW

**Comment by jboxman** [comment]
This is an initial attempt at this. I haven't looked at what happens when `webpack` is run, but the unit tests pass locally.

Looks like I need to tackle `eslint` errors and update the PR.

**Comment by arnog** [comment]
Awesome! Thanks for working on this. 
You will have some es-lint errors about modules being defined but never used. Those modules are in fact used, but they are not referenced, and so this is not an error.

For example, it is necessary to include the OutputLatex module. This module modifies, e.g., MathAtom to add to it some additional functions. However, the OutputLatex module itself is not referenced. Therefore, es-lint need to silenced about those "errors".

**Comment by jboxman** [comment]
Hi! Let me know if there's anything else I can do with this. Thanks.

**Comment by arnog** [comment]
LGTM. If you're done with it, I'll merge it into master. Feel free to close issue #69 with this PR if you'd like.

**Comment by jboxman** [comment]
Cool. Merge away. Thanks!

**Pull request merged**
