### PR TITLE
options for offsetFromPoint, and expose nearestBoxFromPoint

### PR DESCRIPTION
**Pull request by gunnarmein-ts**

### CODE REVIEW

**Comment by arnog** [comment]
Thanks for the PR! Looks good, but I think I would have a `hitboxFromOffset()` function instead: this would be a bit more flexible since you wouldn't need to have a point to get access to the hitbox. What do you think?

**Comment by gunnarmein-ts** [comment]
I am highlighting the element the user is trying to drop on, and the offset gives me only the left or right of it and I am afraid the user will sometimes not understand why.

That said, I could explicitly ask for the left offset (with bias -1) from the point, then use hitBoxFromOffset() to get the same thing? Let me know whether you think that is correct.

From: Arno Gourdol ***@***.***>
Reply-To: arnog/mathlive ***@***.***>
Date: Thursday, September 22, 2022 at 11:35 AM
To: arnog/mathlive ***@***.***>
Cc: Gunnar Mein ***@***.***>, Author ***@***.***>
Subject: Re: [arnog/mathlive] options for offsetFromPoint, and expose nearestBoxFromPoint (PR #1634)


Thanks for the PR! Looks good, but I think I would have a hitboxFromOffset() function instead: this would be a bit more flexible since you wouldn't need to have a point to get access to the hitbox. What do you think?

**Comment by arnog** [comment]
> That said, I could explicitly ask for the left offset (with bias -1) from the point, then use hitBoxFromOffset() to get the same thing? Let me know whether you think that is correct.

Yes, that's what I was thinking. It should still satisfy your use case but gives more options in case someone did not have a point position to start from...

**Comment by gunnarmein-ts** [comment]
I will give it a shot and update when done.

From: Arno Gourdol ***@***.***>
Reply-To: arnog/mathlive ***@***.***>
Date: Thursday, September 22, 2022 at 1:37 PM
To: arnog/mathlive ***@***.***>
Cc: Gunnar Mein ***@***.***>, Author ***@***.***>
Subject: Re: [arnog/mathlive] options for offsetFromPoint, and expose nearestBoxFromPoint (PR #1634)


That said, I could explicitly ask for the left offset (with bias -1) from the point, then use hitBoxFromOffset() to get the same thing? Let me know whether you think that is correct.

Yes, that's what I was thinking. It should still satisfy your use case but gives more options in case someone did not have a point position to start from...

**Comment by gunnarmein-ts** [comment]
Done.

**Review by arnog — APPROVED** [review]

**Pull request merged**
