### PR TITLE
Fix focus bug on iOS 12 and Firefox/Android

### PR DESCRIPTION
**Pull request by beneater**
(and maybe others?)

Test plan:
- Visit /examples/basic/index.esm.html on an iPhone 6
- Tap into mathfield; it gets focus
- Tap around mathfield to move cursor

### CODE REVIEW

**Comment by beneater** [comment]
Hi there! We’ve been using MathLive for the past few weeks in a project we’ve been developing for the [Lockdown Math live video series](https://itempool.com/c/3b1b). MathLive has an impressive amount of functionality!

We had thousands of users banging away on it and received a half-dozen bug reports, all related to not being able to focus the mathfield. The issue seemed to only affect a few iOS safari users and some Firefox users on Android.

I was able to reproduce the issues and the behavior is precisely as described in #208, so maybe that issue hadn’t been completely resolved.

In any event, I could reliably reproduce the issues on Safari on iOS 12.4, which is the latest version of iOS available for a number of devices that are still in use, e.g iPhone 6/7.

The issue is that it appears that in iOS 12.4 Safari and Firefox on Android, the `touchstart` event is sent with `event.buttons = 0` which for a mouse event would normally be an invalid button. There’s some logic in `mathfield-pointer-input.ts` that ignores non-primary-button presses that was also ignoring this case. Consequently the fix appears to be pretty straightforward.

**Comment by arnog** [comment]
Awesome. Thanks for letting me know and for providing a fix. Yeah, it seems like a reasonable fix. 

As an aside, big fan of your work, and love the Lockdown Math live video series (which I didn't know about, but looks really cool). Let me know if you get any other feedback from users that could help improve MathLive.

**Comment by arnog** [comment]
I've published 0.50.8 which incorporates this fix as a GitHub Release and on npm.

**Comment by beneater** [comment]
Awesome, thanks @arnog! Appreciate the release on npm too! We'll let you know as we get more feedback, but so far we've been pretty happy with MathLive.

**Pull request merged**
