### PR TITLE
Fixed: prevent virtual keyboard from closing when clicking on other parts of the kb other than the key elements

### PR DESCRIPTION
**Pull request by xing38**
Fixed issue #1347

### CODE REVIEW

**Review by arnog — APPROVED** [review]
Looks good to me.

**Comment by arnog** [comment]
Thanks for your contribution!

**Comment by hengsok** [comment]
@arnog thanks for merging this! And for all the great effort into this library. Also I have followed you on your IG as I also have photographer hobby, your photos are truly amazing!

**Comment by hengsok** [comment]
@arnog can you push this change to NPM? I really need this fix. Thanks!

**Comment by arnog** [comment]
Thanks!
Done, published mathlive@0.69.11

**Comment by hengsok** [comment]
Thank you! Have a great sunday!

**Pull request merged**
