### PR TITLE
fix: Fixed #934 by moving translate css

### LINKED ISSUE #934: Firefox Nth root symbol missing top line
## Description

When writing the Nth root symbol on Firefox, the element is sometimes cut off by the container so you can't see the top line.

Firefox 88.0.1 (64-bit) on Windows:
image
image
It sometimes appears when other symbols exist in the equation:
image

Chrome 90.0.4430.93 (Official Build) (64-bit) on Windows:
image

## Steps to Reproduce

1. Empty the input
2. Insert a Nth root symbol

### Actual Behavior

The `sqrt-line` element is cropped out in most equation scenarios.

### Expected Behavior

The top line should not be cut off by the math container.

### Environment

https://cortexjs.io/mathlive/guides/virtual-keyboards/

Under the section "Customizing the appearance of the virtual keyboard toggle" with the red keyboard icon.

**Operating System** Windows 10 Pro (Build 19042.928)

### PR DESCRIPTION
**Pull request by manstie**
Even with WebRender enabled on Firefox, the issue still happened sometimes. Moving the translate solves this issue:

image
image

relates to #934

### CODE REVIEW

**Comment by manstie** [comment]
Doesn't fix all cases.

**Comment by manstie** [comment]
Made the PR more concise 🙏

**Comment by arnog** [comment]
Have you tested this fix in other browsers?

**Comment by manstie** [comment]
Firefox Before:
image

https://user-images.githubusercontent.com/12475567/156964808-51da5961-20c9-4fc6-9b6b-758897a271ed.mp4

Firefox After:
image

https://user-images.githubusercontent.com/12475567/156964821-2e309db3-9b2b-43b3-97b8-3a6e6616abc6.mp4

Edge Before:

https://user-images.githubusercontent.com/12475567/156964849-5f8ce570-9b8f-4638-b472-ce55bcd30d6f.mp4

Edge After:

https://user-images.githubusercontent.com/12475567/156964859-d6cb1824-6e69-4286-a284-326b93f273a5.mp4

Chrome Before:

https://user-images.githubusercontent.com/12475567/156964878-e57eb2ef-30c1-43bc-8227-eb2c662eb020.mp4

Chrome After:

https://user-images.githubusercontent.com/12475567/156964896-9dcb871a-af3b-495b-931f-da12dc10f485.mp4

**Comment by arnog** [comment]
Looks good, thanks for the thorough testing. This is unfortunately an area that is pretty fragile and browser dependent and fixes in the past improved things in one browser only to make it worse in another. Long term, the rendering of the bar should be done with SVG to work around the rounding issues definitively...

**Pull request merged**
